# Generated by Django 3.0 on 2021-04-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PERECIVEL', 'Perecíveis'), ('NAO PERECIVEL', 'Não perecíveis')], max_length=30, verbose_name='Tipo de alimento:')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome do produto:')),
                ('descricao', models.TextField(max_length=194, verbose_name='Descrição do produto:')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos:',
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=1000, verbose_name='Quantidade de produto:')),
                ('data_de_validade', models.DateField(verbose_name='Data de validade:')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Produto')),
            ],
        ),
    ]
