# Generated by Django 3.0 on 2021-04-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoestoque',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.AlterModelTable(
            name='produtoestoque',
            table='Estoque',
        ),
    ]
