# Generated by Django 3.0 on 2021-04-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome da empresa:')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail:')),
                ('cep', models.CharField(max_length=194, verbose_name='CEP:')),
                ('pais', models.CharField(max_length=194, verbose_name='País')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado:')),
                ('cidade', models.CharField(max_length=194, verbose_name='Cidade:')),
                ('bairro', models.CharField(max_length=194, verbose_name='Bairro:')),
                ('logradouro', models.CharField(max_length=194, verbose_name='Logradouro:')),
                ('numero_da_casa', models.CharField(max_length=194, verbose_name='Número da residencia ou compleme:')),
                ('CNPJ', models.CharField(max_length=194, unique=True, verbose_name='CNPJ da empresa:')),
                ('telefone', models.CharField(blank=True, max_length=194, null=True, verbose_name='Contato da empresa:')),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastro')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome completo:')),
                ('naturalidade', models.CharField(max_length=194, verbose_name='Naturalidade')),
                ('pais', models.CharField(max_length=194, verbose_name='País')),
                ('escolaridade', models.CharField(choices=[('EFI', 'Ensino fundamental incompleto'), ('EFC', 'Ensino fundamental completo'), ('EMI', 'Ensino médio incompleto'), ('EMC', 'Ensino médio completo'), ('ESI', 'Ensino superior incompleto'), ('ESC', 'Ensino superior completo')], max_length=30, verbose_name='Escolaridade:')),
                ('status', models.CharField(choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Genero')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail:')),
                ('telefone_celular', models.CharField(max_length=19, verbose_name='Número de telefone')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF:')),
                ('nascimento', models.DateField(max_length=10, verbose_name='Data de nascimento:')),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO(A)', 'Solteiro(a)'), ('CASADO(A)', 'Casado(a)'), ('DIVORCIADO(A)', 'Divorciado(a)')], max_length=40, verbose_name='Estado civil:')),
                ('profissao', models.CharField(max_length=194, verbose_name='Profissão:')),
                ('cep', models.CharField(max_length=194, verbose_name='CEP:')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado:')),
                ('cidade', models.CharField(max_length=194, verbose_name='Cidade:')),
                ('bairro', models.CharField(max_length=194, verbose_name='Bairro:')),
                ('logradouro', models.CharField(max_length=194, verbose_name='Logradouro:')),
                ('numero', models.CharField(max_length=194, verbose_name='Número da residencia:')),
                ('telefone', models.CharField(blank=True, max_length=194, null=True, verbose_name='Telefone da residencia:')),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário está ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuário é da equipe de desenvolvimento')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Usuário é um superusuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Empresa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
                'db_table': 'Gerente',
            },
        ),
    ]
