# Generated by Django 3.0 on 2021-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nascimento',
            field=models.DateField(max_length=10, null=True, verbose_name='Data de nascimento:'),
        ),
    ]
