# Generated by Django 3.0 on 2021-04-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='gerente',
            options={'verbose_name': 'Gerente', 'verbose_name_plural': 'Gerentes'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='inscricao_estadual',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(default=1, max_length=194, verbose_name='CEP:'),
            preserve_default=False,
        ),
    ]
