# Generated by Django 3.0 on 2021-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20210408_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='CNPJ',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default=1, max_length=194, unique=True, verbose_name='CNPJ da empresa:'),
            preserve_default=False,
        ),
    ]
