# Generated by Django 3.0 on 2021-04-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20210405_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='E-mail:'),
            preserve_default=False,
        ),
    ]
