# Generated by Django 3.0 on 2021-04-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20210406_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero_da_casa',
            field=models.CharField(max_length=194, verbose_name='Número da residencia ou compleme:'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF:'),
        ),
    ]
