# Generated by Django 3.0 on 2021-04-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('Usuarios', '0002_auto_20210408_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_transacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=30, verbose_name='Tipo de transação:')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da transação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Empresa')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Gerente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Vendedor')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'transacao',
            },
        ),
        migrations.CreateModel(
            name='ProdutosTransacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_de_produtos', models.FloatField(verbose_name='Quantidade de produto:')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Produto')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacao.Transacao')),
            ],
            options={
                'verbose_name': 'Produto de Transação',
                'verbose_name_plural': 'Produtos de transações',
                'db_table': 'produtostransacao',
            },
        ),
    ]
