# Generated by Django 3.0 on 2021-04-07 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_auto_20210407_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da transação'),
            preserve_default=False,
        ),
    ]
