# Generated by Django 3.0 on 2021-04-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0003_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtostransacao',
            old_name='transação',
            new_name='transacao',
        ),
    ]
